language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt update -qq
  - sudo apt install -qq libboost-all-dev
  - export BOOST_ROOT=/usr/local

before_script:
  - mkdir build
  - cd build
  - cmake ../

script:
  - make